[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["full"] }
dotenv = "0.15.0"
log = "0.4.26"
log4rs = "1.3.0"
tokio = { version = "1.44.1", features = ["full"] }
flex_net_core = { path = "../flex_net_core" }
